import 'questions.dart';

class QuizBrain {
  int _questionNumber = 0;

  final List<Question> _questionBank = [
    Question(
        q: 'Venture capitalists are the only source of funding for tech startups..',
        a: false),
    Question(
        q: 'A Minimum Viable Product (MVP) is the final version of a product that is ready for market release.',
        a: false),
    Question(
        q: 'All successful startups follow the same business model.', a: false),
    Question(
        q: 'Intellectual Property (IP) protection is irrelevant for tech startups.',
        a: false),
    Question(
        q: 'Bootstrapping refers to funding a startup using personal savings or revenue generated by the business.',
        a: true),
    Question(
        q: 'Tech startups should focus solely on acquiring a large user base, even if it means operating at a loss.',
        a: false),
    Question(
        q: 'Pivot is a term used when a startup completely abandons its original business idea.',
        a: true),
    Question(
        q: 'Scaling and growth are interchangeable terms in the startup context.',
        a: false),
    Question(
        q: 'All successful startups require a highly experienced and seasoned founding team.',
        a: false),
    Question(
        q: 'A/B testing involves comparing two versions of a webpage or app to determine which one performs better.',
        a: true),
    Question(
        q: 'Tech startups are not affected by market trends or economic conditions.',
        a: false),
    Question(
        q: 'Customer feedback is crucial only during the product development phase, not after the launch.',
        a: false),
  ];

  void nextQuestion() {
    if (_questionNumber < _questionBank.length - 1) {
      _questionNumber++;
    }
  }

  String getQuestion() {
    return _questionBank[_questionNumber].questionText;
  }

  bool getCorrectAnswer() {
    return _questionBank[_questionNumber].questionAnswer;
  }

  bool isFinished() {
    if (_questionNumber >= _questionBank.length - 1) {
      return true;
    } else {
      return false;
    }
  }

  void reset() {
    _questionNumber = 0;
  }
}
